;;; nt-emacs-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from nt-fzf-complete.el

(register-definition-prefixes "nt-fzf-complete" '("nt/fzf-complete-"))


;;; Generated autoloads from nt-magit.el

(autoload 'nt/magit-status "nt-magit" "\
Open magit-status in the current window from vterm, other window otherwise." t)


;;; Generated autoloads from nt-profiler.el

(autoload 'nt/profiler-export-folded-stacks "nt-profiler" "\
Export the current CPU profile as folded stacks to FILENAME.
The output is compatible with Brendan Gregg's flamegraph.pl and inferno.

(fn FILENAME)" t)
(register-definition-prefixes "nt-profiler" '("nt/profiler--format-entry"))


;;; Generated autoloads from nt-projectile.el

(autoload 'nt/projectile-switch-project "nt-projectile" "\
Switch to a project, restoring saved context if available.
Automatically saves window configuration before switching.
With prefix argument ARG, prompt for what to save instead.

(fn &optional ARG)" t)
(autoload 'nt/projectile-save-thing "nt-projectile" "\
Save thing for current project.

Thing is a character representing
-  . point marker
- (b)uffer
- (f)ile
- (w)indow configuration
- (d)elete saved thing

(fn THING)" t)
(register-definition-prefixes "nt-projectile" '("nt/projectile-"))


;;; Generated autoloads from nt-revert.el

(autoload 'nt/revert-buffer "nt-revert" "\
Revert buffer, skipping confirmation when content matches the file on disk." t)

;;; End of scraped data

(provide 'nt-emacs-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nt-emacs-autoloads.el ends here
